name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0

      - name: Cache Zig Packages
        uses: actions/cache@v4
        with:
          path: zig-pkg
          key: ${{ runner.os }}-zig-pkg-${{ hashFiles('build.zig.zon') }}
          restore-keys: |
            ${{ runner.os }}-zig-pkg-

      - name: Build and Test
        run: zig build -Dwith-flexspin install test
